### PR TITLE
bug fix on #226: Zero-initialize numeric variables to prevent garbage…

### LINKED ISSUE #226: [BUG] Defining a 1D array after a 2D array causes incorrect sum results for 2D array
**Describe the bug**
The definition of a 1D array after a 2D array causes an incorrect sum of the 2D array

**To Reproduce**
This works and produces the expect total sum of 24:
```
//> cflags: -fopenmp
import "omp.h"

fn main() {
  def n = 3
  let a: float[4][n] = [[1,2,3], [1,2,3], [1,2,3], [1,2,3]]
  // let b = [1,2,3]            // -------------------> Problematic Line
  let sum: int

  #pragma omp parallel reduction(+:sum)
  {
    let myid = omp_get_thread_num()
    for i in 0 .. n {
      sum += a[myid][i]
    }
  }

  println "{sum}"
}
```
If you uncomment the ```problematic line```, the program outs the sum ```32789```.

**Expected behavior**
Should print 24.

**Screenshots**
This is the output with the problematic line uncommented:
```
     Running a.out
32789
```

**Environment (please complete the following information):**
 - OS: Ubuntu 25.10
 - Zen C Version: v0.4.1-2-gdbba574
 - Compiler: GCC 15.2

### PR DESCRIPTION
**Pull request by iryuken**
Fix bug #226: Zero-initialize all numeric variables

## Description
This PR fixes bug #226 where numeric variables (like [int](cci:1://file:///Zen-C/src/ast/ast.c:103:0-128:1), [float](cci:1://file:///src/ast/ast.c:130:0-138:1)) declared without an explicit initializer were left uninitialized in the generated C code. This caused garbage values on the stack to be used in computations, as observed in the issue where an OpenMP reduction sum started with a large garbage value (`32789` instead of `24`).

The fix updates [src/codegen/codegen_stmt.c](cci:7://file:///Zen-C/src/codegen/codegen_stmt.c:0:0-0:0) to ensure **all** local variables without initializers are zero-initialized by default (`= 0` for numerics, `= {0}` for aggregates).

Fixes #226

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/codegen/codegen_stmt.c [hunk 1]
```diff
@@ -972,12 +972,17 @@ void codegen_node_single(ParserContext *ctx, ASTNode *node, FILE *out)
...
-                    // Zero initialize arrays and structs by default so we don't have garbage
-                    fprintf(out, " = {0}");
+                    // Zero initialize all variables by default so we don't have garbage
+                    if (node->type_info->kind == TYPE_ARRAY || node->type_info->kind == TYPE_STRUCT)
+                    {
+                        fprintf(out, " = {0}");
+                    }
+                    else
+                    {
+                        fprintf(out, " = 0");
```
Comment (Burnett01) [inline src/codegen/codegen_stmt.c]: I am not sure if we should really zero-initialize ``all`` by default. The code of issue #226 is dealing with int (sum) hence I'm leaning towards only zero-initializing type int.

- How does this code change behave with other arithmetic types?

Comment (iryuken) [reply src/codegen/codegen_stmt.c]: Yes, absolutely! The latest commit re-enables zero-initialization for arrays and structs (`= {0}`) as well as integer types (`= 0`).

So `let x: [int;5]` will definitely still work and be zero-initialized.

The only things left uninitialized now are floating point types and pointers
